### ISSUE TITLE
Changing a PlotGenerator object is not reflected in the dashboard

### ISSUE THREAD

**Issue by galwiner** [entropy-lab/entropy#186]
If they dashboard is being served and a user makes a change to a PlotGenerator object, these changes are not reflected in the dashboard unless the process is killed and restarted. 

opened on behalf of user @ilanmitnikov

**Comment by urig** [comment]
Hi @galwiner. It would help me out if you could be a bit more specific about what changes to the PlotGenerator object are?
I.e steps to reproduce: I run the dashboard, display a plot generate from a PlotGenerator and then I change the code of the PlotGenerator? Also what is your expectation? That the change be reflected immediately? Following a page refresh? Thanks :)

**Comment by urig** [comment]
Hi. I've investigated this and the root cause seems to be that Dash's "hot reload" feature is not working for us because we serve our Dash app using the [waitress ](https://github.com/Pylons/waitress) WSGI server.

I've opened a [Dash issue](https://github.com/plotly/dash/issues/1955) for this and will track it.

I will now create a PR with a workaround from a [stackoverflow answer](https://stackoverflow.com/a/61920542/33404) that I've found and tested.

**Comment by urig** [comment]
Update: The method in the stackoverflow answer above is based on an API from werkzeug that is now deprecated. I am creating a PR based on a different solution = the [hupper](https://docs.pylonsproject.org/projects/hupper/en/latest/index.html)process montioring library.

**Comment by urig** [comment]
@galwiner I think this can be closed now. Thanks.
