### ISSUE TITLE
Should we reraise exceptions in the execution flow?

### ISSUE THREAD

**Issue by talshani** [entropy-lab/entropy#75]
Currently, we catch all exceptions in the normal. This is against the usecase

> As a user, if an exception is thrown from my experiment code, I would like to have it available to me when a RuntimeError is thrown in experiment.py, line 94

**Comment by talshani** [comment]
@urig note this is per your comment

**Comment by galwiner** [comment]
@nikolaqm

**Comment by nikolaqm** [comment]
We have to fail-fast, so that problem is well localized at lowest level possible. Like a safety glass, we want small modules.
So if we can show exception as soon as possible it would be great. For current entropy, at least printout on standard output.
For next Entropy, this type of visibility is prime consideration.
